Mobs:
  Global:
    MobSpawnerModifier: 0.5 # Mob drops from mobs that have spawned from spawners will be decreased by 1/2
    Hive: # If a player attacks a mob, mobs within this range will automatically target towards the player
      HorizontalRange: 30
      VerticalRange: 10
      Sound:
        Name: UI_BUTTON_CLICK
        Volume: 0.5
        Pitch: 0.05
        Rate: 5
    Loot: # Global loot for all Monsters
      block:
        Icon: GOLD_BLOCK
        Amount: 2
        Probability: 0.0025
      block2:
        Icon: GOLD_BLOCK
        Probability: 0.00333
      gapple:
        Icon: GOLDEN_APPLE
        Probability: 0.004
      gingot:
        Icon: GOLD_INGOT
        Amount: 2
        Probability: 0.005
      gingot2:
        Icon: GOLD_INGOT
        Probability: 0.01
      gore:
        Icon: GOLD_ORE
        Probability: 0.0113
      gnug:
        Icon: GOLD_NUGGET
        Amount: 3
        Probability: 0.0125
      gnug1:
        Icon: GOLD_NUGGET
        Amount: 2
        Probability: 0.0285
      gnug3:
        Icon: GOLD_NUGGET
        Amount: 1
        Probability: 0.05
  Blaze:
    Particles:
      Speed: 0.1
      Lines: 20
      YRate: 400
    Spawning: # Blazes can spawn in these blocks
      ValidBlocks:
      - LAVA
      Probability: 0.4
    Fireballs: # How powerful the blaze fireballs are
      Power: 1.5
  Creeper:
    FuseTicks: 15 # Default is 30
    TNTRate: 0.05 # How likely a creeper is to spawn TNT when it dies
    TNTPowered: true # If true, creepers will always spawn TNT if it is powered
  Enderman:
    UntargetDistanceSquared: 2500 # Distance (squared) for endermen to forget about its target (2500 = 50 blocks)
    Damage: 5.5 # Damage the enderman will deal
    Chuck: # Enderman will throw a block at the player
      Probability: 0.7 # Probability that the enderman will pickup a block
      StartDelay: 60 # Time in ticks for this attack to start
      PeriodDelay: 40 # Repeat in ticks for the enderman to attempt to throw/pickup a block
      Sound:
        Name: ENTITY_ENDERMAN_SCREAM
        Volume: 2
        Pitch: 1
    GrabTeleport: # Enderman will pickup the player and chuck them to the ground
      Probability:
        Regular: 0.6 # Probability that this will happen if the player isn't blocking with a shield
        Blocking: 0.15
    TeleportBehind: # Enderman will teleport behind an attacker
      Probability: 0.4
      MinimumDistance: 25 # 5 Blocks
      Distance: # Positive to teleport infront of attacker
        Minimum: -3
        Maximum: -1
  Ghast:
    UntargetDistanceSquared: 2500
    Spawning:
      BlockHeight: 235 # Ghasts can spawn if a player places a block above this Y level
      MessageCooldown: 600 # 600 seconds
      MessageOnPlace: An odd presence says you shouldn't place blocks this high...
      MessageOnSpawn: You should have listened...
      HorizontalRange: 30
      VerticalRange: 5
      Probability: 0.05
    Shoot:
      StartDelay: 10
      PeriodDelay: 120
  Skeleton:
    UntargetDistanceSquared: 2500
    Speed: 0.52 # Speed for the skeleton, default is .50
    FastArrow:
      StartDelay: 10
      PeriodDelay: 40
    Respawn:
      Probability: 0.25
      Time: 3000 # 3 seconds
      RespawningParticles: FLAME
      Sounds:
        Respawning:
          Name: ENTITY_SKELETON_AMBIENT
          Volume: 2
          Pitch: 0.1
          Rate: 200
        Respawned:
          Name: ENTITY_BLAZE_AMBIENT
          Volume: 2
          Pitch: 0.25
  Slime:
    Charge:
      StartDelay: 25
      PeriodDelay: 80
    SizeIncrease:
      Probability: 0.2
      MaxSize: 5
      Sound:
        Name: BLOCK_SLIME_BLOCK_FALL
        Volume: 2
        Pitch: 1
    SlowAttack:
      MinimumSize: 2
      Probability: 0.30
      Duration: 100
      Power:
        Minimum: 1
        Maximum: 3
  Spider:
    Health: 11
    Speed: 0.62
    CobThrow:
      StartDelay: 20
      NextShot:
        Minimum: 500
        Maximum: 6000
      Material: COBWEB
  Witch:
    BatSpawn:
      Probability: 0.2
    Potions:
      LEVITATION:
        Probability: 0.02
        Duration: 100
        Level: 2
      REGENERATION:
        Probability: 0.03
        Duration: 140
        Level: 0
      DAMAGE_RESISTANCE:
        Probability: 0.025
        Duration: 400
        Level: 1
      SPEED:
        Probability: 0.028
        Duration: 200
        Level: 2
  Zombie:
    SpawnNew:
      Probability: 0.3
      Radius: 5
      BabyProbability: 0.8
    Respawn:
      Probability: 0.2
      Time: 2000
      RespawningParticles: SMOKE_NORMAL
      Sounds:
        Respawning:
          Name: ENTITY_ZOMBIE_HURT
          Volume: 2
          Pitch: 0.1
          Rate: 800
        Respawned:
          Name: ENTITY_SKELETON_HURT
          Volume: 2
          Pitch: 0.1
    InflictEffects:
      WEAKNESS:
        Duration: 600
        Level: 0
        Probability: 0.0192307692307692
      SLOW:
        Duration: 200
        Level: 1
        Probability: 0.0357142857142857?
      POISON:
        Duration: 300
        Level: 0
        Probability: 0.0212765957446809
      WITHER:
        Duration: 100
        Level: 1
        Probability: 0.03125
      BLINDNESS:
        Duration: 400
        Level: 0
        Probability: 0.04
    SpawnItems:
      dsword:
        Icon: DIAMOND_SWORD
        Probability: 0.01
      wsword:
        Icon: WOODEN_SWORD
        Enchantments:
        - DAMAGE_ALL:1
      waxe:
        Icon: WOODEN_AXE
        Probability: 0.018
      rod:
        Icon: FISHING_ROD
        Enchantments:
        - VANISHING_CURSE:1
        Probability: 0.02
      goldnugget:
        Icon: GOLD_NUGGET
        Probability: 0.0285
      stone:
        Icon: STONE
        Probability: 0.0217
      ironsword:
        Icon: IRON_SWORD
        Probability: 0.0133
      stonesword:
        Icon: STONE_SWORD
        Enchantments:
        - DURABILITY:2
        Probability: 0.01923
      goldshovel:
        Icon: GOLDEN_SHOVEL
        Enchantments:
        - DIG_SPEED:1
        Probability: 0.0138
      stick:
        Icon: STICK
        Probability: 0.0277
      redstone:
        Icon: REDSTONE
        Probability: 0.0121
      daxe:
        Icon: DIAMOND_AXE
        Enchantments:
        - DAMAGE_UNDEAD:4
        Probability: 0.0117
Attacks:
# Spiders use this attack
  BlockItemThrow: # The attacker throws a block at the target in the form of an item
    MinimumDistance: 100 # Target must be within 10 blocks
    Multiplier: 0.8
    YOffset: 0.5 # Speed of item
    TeleportRange: 1 # Add .5 to the current velocity
    LiveTime: 10000 # ms
    Damage: 3
    HitSound:
      Name: ENTITY_EXPERIENCE_ORB_PICKUP
      Volume: 1
      Pitch: 2
    RemoveBlockAfter: 400
# Endermen user this attack
  BlockPhysicThrow: # The attacker throws a physical block at the target
    MinimumDistance: 100
    Multiplier: 0.8
    YMultiplier: 1.2
    Damage:
      HorizontalRange: 2
      VerticalRange: 2
      Damage: 8
    HitSound:
      Name: BLOCK_ANVIL_LAND
      Volume: 1
      Pitch: 0.11
# Slimes use this attack
  ChargeAtAttack: # The attacker "charges" itself at the target
    RelativeMultiplier: 0.5
    LaunchSound:
      Name: ENTITY_PLAYER_ATTACK_SWEEP
      Volume: 2
      Pitch: 0.1
    HitboxLifetime: 3000 # The attack will end after this many ms
    Damage: 3 # Damage will scale automatically with slimes, additionally, damage is automatically scaled by 2 for mobs that aren't slimes
    HitSound:
      Name: ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR
      Volume: 1
      Pitch: 0.3
# Skeletons use this attack
  FastArrowAttack: # The attacker launches an arrow directed at the player
    ShootSound:
      Name: ENTITY_ARROW_SHOOT
      Volume: 1
      Pitch: 2
    Multiplier: 0.3
    Particles:
      MaxParticles: 200
      PaticlesPerBlock: 2
      ParticleType: FLAME
# Ghasts use this attack
  FireballAttack: # The attacker shoots fireball(s) that can seek towards the target
    Speed: 7
    Accuracy: 0.15
    Power: 2
    Fireballs: 5
    ShootSound:
      Name: ENTITY_BLAZE_SHOOT
      Volume: 2
      Pitch: 1
# Endermen use this attack
  GrabSlamAttack: # The attacker will grab the player, go up into the air, and slam the player into the ground
    GrabTime: 500 # How long until the attacker goes up into the air
    UpVelocity: 2.5
    ThrowVelocity: -1.8
    ThrowSound:
      Name: ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR
      Volume: 2
      Pitch: 1
      Velocity: 2.5
# Creepers use this attack
  TNTAttack: # The attacker will spawn a TNT
    Velocity:
      X: 0
      Y: 2
      Z: 0
    Ticks: 72
    Power: 5
DebugMode:
  Enabled: true
  Allow:
  - MSWS